name: Bug Report
description: Report a reproducible bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: checkboxes
    id: preflight
    attributes:
      label: Before submitting
      options:
        - label: I have searched [existing issues](https://github.com/sup3rus3r/obsidian-ai/issues) and this has not been reported
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions to reliably reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Area affected
      options:
        - Backend / API
        - Frontend / UI
        - Agent / Multi-Agent
        - Workflow / Scheduler
        - LLM Provider / Model
        - RAG / Knowledge Base
        - MCP / Tool Integration
        - Authentication / Security
        - Database (SQLite / MongoDB)
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. Ubuntu 24.04, macOS 14, Windows 11
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python version
      placeholder: e.g. 3.12.3
    validations:
      required: true

  - type: input
    id: node_version
    attributes:
      label: Node.js version
      placeholder: e.g. 20.11.0

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error output
      description: Paste any relevant logs. Redact API keys and secrets before posting.
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, recordings, or any other information that may help.
